hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: update

Spring:
  datasource:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ""